version: 1.0

server:
  host: 0.0.0.0
  port: 8001
databases:
  postgres:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    db: aspire
    sslmode: disable
    connect_timeout: 10